[package]
name = "AlphaTOTP"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full", "test-util"] } # For asynchronous runtime
chrono = "0.4"
hmac = "0.12"
sha2 = "0.10"
base32 = "0.5.1"
clap = "2.33"
rand = "0.8"

